name: Build and Publish Docker Image

# Controls when the workflow will run
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Show me some variables
        run: |
          echo $GITHUB_HEAD_REF;
          echo $GITHUB_BASE_REF;
          echo $GITHUB_REF;
          echo $GITHUB_WORKSPACE;
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV;
          env | sort

      - name: Install coreutils and gettext
        run: |
          sudo apt update
          sudo apt install -y coreutils gettext

      - name: Build and publish image
        run: ./bin/ci.sh run